build: false

environment:
    PYTHON: "C:\\Python37"
    CVPLOT_CI_BRANCH: {APPVEYOR_REPO_BRANCH}
    CONAN_USERNAME: "profactor-public"
    CONAN_LOGIN_USERNAME: "wpalfi"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/profactor/conan"
    CONAN_ARCHS: x86_64
    #CONAN_BUILD_TYPES: Release
    #CONAN_VISUAL_RUNTIMES: MD
    CONAN_STABLE_BRANCH_PATTERN: i-will-tell-you-when-something-is-stable

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
